# 2026-03-26	mise-en-place configuration

[env]
LOCAL_FOLDER = 'dist'
NPM = 'pnpm'
REMOTE_FOLDER = 'chgroup'
REMOTE_HOST = 'fd-debian-scw'
REMOTE_PATH = '/data/nginx/www'

[hooks]
enter = { task = "enter" }

[tasks.enter]
run = '''
ls -alt --color
echo ''
mise shell-alias
echo ''
'''

[shell_alias]
als = "mise shell-alias"
bld = "${NPM} run build"
check = "${NPM} run check"
clean = "${NPM} run clean"
deploy = "rsync -r -v ${LOCAL_FOLDER}/ ${REMOTE_HOST}:${REMOTE_PATH}/${REMOTE_FOLDER}"
dev = "${NPM} run dev"
fmtchk = "${NPM} run fmt:check"
fmtfix = "${NPM} run fmt:fix"
